load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_test")

rust_binary(
    name = "capnp_cli",
    srcs = ["src/main.rs"],
    crate_name = "capnp_cli",
    edition = "2024",
    deps = [
        "//crates/capnp-compiler:capnp_compiler",
        "//crates/capnp-io:capnp_io",
    ],
    visibility = ["//visibility:public"],
)

rust_test(
    name = "capnp_cli_test",
    crate = ":capnp_cli",
)

