load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "capnp_compiler",
    srcs = [
        "src/lib.rs",
        "src/semantic.rs",
    ],
    crate_name = "capnp_compiler",
    edition = "2024",
    deps = [
        "//crates/capnp-schema:capnp_schema",
    ],
    visibility = ["//visibility:public"],
)

rust_test(
    name = "capnp_compiler_test",
    crate = ":capnp_compiler",
    compile_data = [
        "//conformance:compiler_requests",
        "//conformance:schema_source_corpus",
    ],
)
