load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "capnp_message",
    srcs = ["src/lib.rs"],
    crate_name = "capnp_message",
    edition = "2024",
    deps = [
        "//crates/capnp-wire:capnp_wire",
    ],
    visibility = ["//visibility:public"],
)

rust_test(
    name = "capnp_message_test",
    crate = ":capnp_message",
)

