[package]
name = "capnp-message"
description = "Readers, builders, budgets, copying, orphans, and canonicalization"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true
repository.workspace = true

[features]
loom-tests = ["dep:loom"]

[lints]
workspace = true

[dependencies]
capnp-wire = { path = "../capnp-wire" }
loom = { version = "0.7.2", optional = true }
