load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "capnp_async",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "capnp_async",
    edition = "2024",
    deps = [
        "//crates/capnp-wire:capnp_wire",
        "//crates/capnp-message:capnp_message",
        "//crates/capnp-io:capnp_io",
    ],
    visibility = ["//visibility:public"],
)

rust_test(
    name = "capnp_async_test",
    crate = ":capnp_async",
    compile_data = ["//conformance:cpp_wire_frames"],
)
