load("@rules_shell//shell:sh_test.bzl", "sh_test")

sh_test(
    name = "upstream_schema_hashes_test",
    srcs = ["verify-upstream-schema-files.sh"],
    data = [
        "upstream/capnproto/e7c9cd96f1505b5ae486db7821006c2f5dce5b5b/persistent.capnp",
        "upstream/capnproto/e7c9cd96f1505b5ae486db7821006c2f5dce5b5b/rpc-twoparty.capnp",
        "upstream/capnproto/e7c9cd96f1505b5ae486db7821006c2f5dce5b5b/rpc.capnp",
        "upstream/capnproto/e7c9cd96f1505b5ae486db7821006c2f5dce5b5b/schema.capnp",
    ],
)

sh_test(
    name = "cpp_fixture_hashes_test",
    srcs = ["verify-cpp-fixtures.sh"],
    data = glob([
        "fixtures/cpp/**",
        "fixtures/source/**",
    ]) + ["//conformance/schemas:schema_files"],
)

sh_test(
    name = "rust_fixture_hashes_test",
    srcs = ["verify-rust-fixtures.sh"],
    data = glob(["fixtures/capnproto-rust/**"])
        + ["//conformance/schemas:schema_files"],
)
