load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "capnp_compat",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "capnp_compat",
    edition = "2024",
    deps = [
        "//crates/capnp-json:capnp_json",
        "//crates/capnp-message:capnp_message",
        "//crates/capnp-schema:capnp_schema",
    ],
    visibility = ["//visibility:public"],
)

rust_test(
    name = "capnp_compat_test",
    crate = ":capnp_compat",
)
