load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "capnp_schema",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "capnp_schema",
    edition = "2024",
    deps = [
        "//crates/capnp-io:capnp_io",
        "//crates/capnp-message:capnp_message",
    ],
    visibility = ["//visibility:public"],
)

rust_test(
    name = "capnp_schema_test",
    crate = ":capnp_schema",
    compile_data = ["//conformance:compiler_requests"],
)
