load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "capnp_rpc_core",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "capnp_rpc_core",
    compile_data = ["schema/rpc-protocol-request.bin"],
    edition = "2024",
    deps = [
        "//crates/capnp-message:capnp_message",
        "//crates/capnp-schema:capnp_schema",
    ],
    visibility = ["//visibility:public"],
)

rust_test(
    name = "capnp_rpc_core_test",
    crate = ":capnp_rpc_core",
)
